[workspace]
authors = ["Hameer Abbasi <2190658+hameerabbasi@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "hameerabbasi.github.io"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
build = { cmd = "zola build", cwd = "blog" }
serve = { cmd = "zola serve", cwd = "blog" }

[dependencies]
zola = ">=0.22.1"
